import { JetBrains_Mono } from "next/font/google"; 
import "./globals.css";

//components
import Header from "@/components/Header";

const JetBrainsMono = JetBrains_Mono({ 
  subsets: ["latin"],
  weights: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-JetBrainsMono", 
}); 

export const metadata = {
  title: "Asanka",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.className}> 
        <Header />
        {children}
      </body>
    </html>
  );
}
